/**********************************************************
 * This file is generated by 20-sim C++ Code Generator
 *
 *  file:  test_PositionControllerPan.cpp
 *  subm:  PositionControllerPan
 *  model: Jiwy-1
 *  expmt: Jiwy-1
 *  date:  May 28, 2026
 *  time:  8:39:44 AM
 *  user:  20-sim 5.1 Professional
 *  from:  Demo/Viewer License
 *  build: 5.1.6.14106
 **********************************************************/

/* This file is a demo application of how the submodel function can
 * be used. It uses the global time variables that are used by both
 * the submodel and the integration method.
 *
 * PLEASE NOTE: THIS IS AN EXAMPLE WHERE ALL INPUTS ARE ZERO !
 * USE YOUR OWN INPUTS INSTEAD!! ALSO THE SUBMODEL MIGHT SIMPLY
 * NOT WORK CORRECTLY WITH INPUTS THAT ARE ZERO.
 */

#include <stdio.h>
#include <cstdint>
#include <string.h>
#include <time.h>
#include <unistd.h>

/* 20-sim submodel class include file */
#include "Pancpp/PositionControllerPan.h"
#include "Tiltcpp/PositionControllerTilt.h"
#include "FPGA_Interface.hpp"

#define SPI_CHANNEL 1
#define SPI_SPEED 1000000
#define SPI_FLAGS 0

#define DIRECTION_BIT_OFFSET 8

#define TILTCONST 681/2.62
#define PANCONST 681/2.62

#define TIME_STEP_MS 10

/* the main function */
int main()
{
	char RXBuf[8]; 
	char TXBuf[8];
	int spi = FPGAInterface::spiOpen(SPI_CHANNEL, SPI_SPEED, SPI_FLAGS);

	XXDouble ut [3 + 1];
	XXDouble yt [1 + 1];
    XXDouble up [2 + 1];
    XXDouble yp [2 + 1];
	XXDouble u [2 + 1];
	XXDouble y [2 + 1];

	uint16_t panEncoderValue = 0;
	uint16_t tiltEncoderValue = 0;
	XXDouble panPosition = 0;
	XXDouble tiltPosition = 0;


	uint32_t homingControlSignal = ((1 << DIRECTION_BIT_OFFSET) | (25 << 16)) | ((1 << DIRECTION_BIT_OFFSET) | 25);
	memcpy(&TXBuf[0], &homingControlSignal, sizeof(uint32_t));
	FPGAInterface::spiWrite(spi, SPI_SPEED, TXBuf, 8);
	sleep(3);

	FPGAInterface::spiRead(spi, SPI_SPEED, RXBuf, 8);
	memcpy(&panEncoderValue, &RXBuf[0], sizeof(uint16_t));
	memcpy(&tiltEncoderValue, &RXBuf[2], sizeof(uint16_t));
	panPosition = panEncoderValue / PANCONST;
	tiltPosition = tiltEncoderValue / TILTCONST;


	/* initialize the inputs and outputs with correct initial values */
	ut[0] = 0.0;		/* corr */
	ut[1] = tiltPosition;		/* in */
	ut[2] = tiltPosition;		/* position */

	yt[0] = 0.0;		/* out */

    up[0] = panPosition;		/* in */
	up[1] = panPosition;		/* position */

	yp[0] = 0.0;		/* corr */
	yp[1] = 0.0;		/* out */

	PositionControllerPan panController;
    PositionControllerTilt tiltController;

	/* initialize the submodel itself and calculate the outputs for t=0.0 */
	panController.Initialize(up, yp, 0.0);
    tiltController.Initialize(ut, yt, 0.0);
	printf("Time pan: %f\n", panController.GetTime() );
	printf("Time tilt: %f\n", tiltController.GetTime() );

	int nextTime = clock() + TIME_STEP_MS;

	/* simple loop, the time is incremented by the integration method */
	while (panController.state != PositionControllerPan::finished && tiltController.state != PositionControllerTilt::finished)
	{
		FPGAInterface::spiRead(spi, SPI_SPEED, RXBuf, 8);

		memcpy(&panEncoderValue, &RXBuf[0], sizeof(uint16_t));
		memcpy(&tiltEncoderValue, &RXBuf[2], sizeof(uint16_t));

		XXDouble panPosition = panEncoderValue / PANCONST;
		XXDouble tiltPosition = tiltEncoderValue / TILTCONST;

		if (clock() > nextTime) {

			/* call the submodel to calculate the output */
			up[1] = (XXDouble)panPosition;	// panPosition is the position value from the pan encoder
			ut[2] = (XXDouble)tiltPosition; // tiltPosition is the position value from the tilt encoder
			panController.Calculate(up, yp);
			ut[0] = yp[0];
			tiltController.Calculate(ut, yt);

			uint32_t panControlSignal;
			if (yp[1] > 0)
			{
				panControlSignal = 1 << 8 | ((uint8_t)yp[1] * 100);
			}
			else if (yp[1] < 0)
			{
				panControlSignal = 0 << 8 | ((uint8_t)(-yp[1]) * 100);
			}
			else
			{
				panControlSignal = 0;
			}

			uint32_t tiltControlSignal;
			if (yt[0] > 0)
			{
				tiltControlSignal = 1 << 8 | ((uint8_t)yt[0] * 100);
			}
			else if (yt[0] < 0)
			{
				tiltControlSignal = 0 << 8 | ((uint8_t)(-yt[0]) * 100);
			}
			else
			{
				tiltControlSignal = 0;
			}

			memcpy(&TXBuf[0], &panControlSignal, sizeof(uint16_t));
			memcpy(&TXBuf[2], &tiltControlSignal, sizeof(uint16_t));

			FPGAInterface::spiWrite(spi, SPI_SPEED, TXBuf, 8);
			printf("Time pan: %f\n", panController.GetTime());
			printf("Time tilt: %f\n", tiltController.GetTime());
			nextTime += TIME_STEP_MS;
		}
	}

	/* perform the final calculations */
	panController.Terminate (up, yp);
    tiltController.Terminate (ut, yt);

	/* and we are done */
	return 0;
}

