/**********************************************************
 * This file is generated by 20-sim C++ Code Generator
 *
 *  file:  test_PositionControllerPan.cpp
 *  subm:  PositionControllerPan
 *  model: Jiwy-1
 *  expmt: Jiwy-1
 *  date:  May 28, 2026
 *  time:  8:39:44 AM
 *  user:  20-sim 5.1 Professional
 *  from:  Demo/Viewer License
 *  build: 5.1.6.14106
 **********************************************************/

/* This file is a demo application of how the submodel function can
 * be used. It uses the global time variables that are used by both
 * the submodel and the integration method.
 *
 * PLEASE NOTE: THIS IS AN EXAMPLE WHERE ALL INPUTS ARE ZERO !
 * USE YOUR OWN INPUTS INSTEAD!! ALSO THE SUBMODEL MIGHT SIMPLY
 * NOT WORK CORRECTLY WITH INPUTS THAT ARE ZERO.
 */

#include <stdio.h>
#include <cstdint>
#include <string.h>
#include <time.h>
#include <fcntl.h>
#include <sys/mman.h>
#include <unistd.h>

/* 20-sim submodel class include file */
#include "FullController/FullController.h"
#include "soc_system.h"

#define SPI_CHANNEL 1
#define SPI_SPEED 1000000
#define SPI_FLAGS 0

#define DIRECTION_BIT_OFFSET 8

#define TIME_STEP_MS 10

#define TILTCONST 681 / 2.62
#define PANCONST 681 / 2.62

/* the main function */
int main()
{
	int fd = 0;

	fd = open("/dev/mem", O_RDWR | O_SYNC);
	if (fd < 0)
	{
		perror("Couldn't open /dev/mem\n");
		return -1;
	}
	uint8_t *esl_demo_map = NULL;
	esl_demo_map = (uint8_t *)mmap(NULL, HPS_0_ARM_A9_0_TOPENTITY_0_SPAN, PROT_READ | PROT_WRITE, MAP_SHARED, fd, HPS_0_ARM_A9_0_TOPENTITY_0_BASE);
	if (esl_demo_map == MAP_FAILED)
	{
		perror("Couldn't map bridge.");
		close(fd);
		return -1;
	}

	XXDouble u[4 + 1];
	XXDouble y[2 + 1];

	uint32_t encoderValues = 0;
	uint16_t panEncoderValue = 0;
	uint16_t tiltEncoderValue = 0;
	XXDouble panPosition = 0.0;
	XXDouble tiltPosition = 0.0;

	// Homing procedure, move at 25% speed in one direction
	*((uint32_t *)esl_demo_map) = (((1 << DIRECTION_BIT_OFFSET) | 10) << 16 ) | ((1 << DIRECTION_BIT_OFFSET) | 10);
	sleep(3);
	*((uint32_t *)esl_demo_map) = 0;
	// We don't actually understand how the avalon bus switches between read and write so we just wait 30 ms
	usleep(30);
	encoderValues = *((uint32_t *)esl_demo_map);
	panEncoderValue = *((uint16_t *)esl_demo_map);
	tiltEncoderValue = (uint16_t)(encoderValues << 16);

	panPosition = panEncoderValue / PANCONST;
	tiltPosition = tiltEncoderValue / TILTCONST;

	/* initialize the inputs and outputs with correct initial values */
	u[0] = panPosition;	 /* PosPan */
	u[1] = tiltPosition; /* PosTilt */
	u[2] = panPosition;	 /* RefPan */
	u[3] = tiltPosition; /* RefTilt */

	y[0] = 0.0; /* OutPan */
	y[1] = 0.0; /* OutTilt */

	FullController my20simSubmodel;

	/* initialize the submodel itself and calculate the outputs for t=0.0 */
	my20simSubmodel.Initialize(u, y, 0.0);
	printf("Time: %f\n", my20simSubmodel.GetTime());

	int nextTime = clock() + TIME_STEP_MS;

	/* simple loop, the time is incremented by the integration method */
	while (my20simSubmodel.state != FullController::finished)
	{
		// Read encoder values
		encoderValues = *((uint32_t *)esl_demo_map);
		panEncoderValue = *((uint16_t *)esl_demo_map);
		tiltEncoderValue = (uint16_t)(encoderValues >> 16);
		printf("Encoder values: pan = %d, tilt = %d\n", panEncoderValue, tiltEncoderValue);

		panPosition = panEncoderValue / PANCONST;
		tiltPosition = tiltEncoderValue / TILTCONST;
		if (clock() >= nextTime)
		{

			/* call the submodel to calculate the output */
			u[0] = (XXDouble)panPosition;  // panPosition is the position value from the pan encoder
			u[1] = (XXDouble)tiltPosition; // tiltPosition is the position value from the tilt encoder
			my20simSubmodel.Calculate(u, y);

			uint16_t panControlSignal;
			if (y[0] > 0)
			{
				panControlSignal = 1 << DIRECTION_BIT_OFFSET | ((uint8_t)y[0] * 100);
			}
			else if (y[1] < 0)
			{
				panControlSignal = 0 << DIRECTION_BIT_OFFSET | ((uint8_t)(-y[1]) * 100);
			}
			else
			{
				panControlSignal = 0;
			}

			uint16_t tiltControlSignal;
			if (y[1] > 0)
			{
				tiltControlSignal = 1 << DIRECTION_BIT_OFFSET | ((uint8_t)y[1] * 100);
			}
			else if (y[0] < 0)
			{
				tiltControlSignal = 0 << DIRECTION_BIT_OFFSET | ((uint8_t)(-y[0]) * 100);
			}
			else
			{
				tiltControlSignal = 0;
			}

			*((uint32_t *)esl_demo_map) = (tiltControlSignal << 16) | panControlSignal;

			printf("Time: %f\n", my20simSubmodel.GetTime());
			nextTime += TIME_STEP_MS;
		}
	}

	/* perform the final calculations */
	my20simSubmodel.Terminate(u, y);

	munmap(esl_demo_map, HPS_0_ARM_A9_0_TOPENTITY_0_SPAN);
	close(fd);

	/* and we are done */
	return 0;
}
