/**********************************************************
 * This file is generated by 20-sim C++ Code Generator
 *
 *  file:  test_PositionControllerPan.cpp
 *  subm:  PositionControllerPan
 *  model: Jiwy-1
 *  expmt: Jiwy-1
 *  date:  May 28, 2026
 *  time:  8:39:44 AM
 *  user:  20-sim 5.1 Professional
 *  from:  Demo/Viewer License
 *  build: 5.1.6.14106
 **********************************************************/

/* This file is a demo application of how the submodel function can
 * be used. It uses the global time variables that are used by both
 * the submodel and the integration method.
 *
 * PLEASE NOTE: THIS IS AN EXAMPLE WHERE ALL INPUTS ARE ZERO !
 * USE YOUR OWN INPUTS INSTEAD!! ALSO THE SUBMODEL MIGHT SIMPLY
 * NOT WORK CORRECTLY WITH INPUTS THAT ARE ZERO.
 */

#include <stdio.h>

/* 20-sim submodel class include file */
#include "Pancpp/PositionControllerPan.h"
#include "Tiltcpp/PositionControllerTilt.h"

/* the main function */
int main()
{
	XXDouble ut [3 + 1];
	XXDouble yt [1 + 1];
    XXDouble up [2 + 1];
    XXDouble yp [2 + 1];

	/* initialize the inputs and outputs with correct initial values */
	ut[0] = 0.0;		/* corr */
	ut[1] = 0.0;		/* in */
	ut[2] = 0.0;		/* position */

	yt[0] = 0.0;		/* out */

    up[0] = 0.0;		/* in */
	up[1] = 0.0;		/* position */

	yp[0] = 0.0;		/* corr */
	yp[1] = 0.0;		/* out */

	PositionControllerPan panController;
    PositionControllerTilt tiltController;

	/* initialize the submodel itself and calculate the outputs for t=0.0 */
	panController.Initialize(up, yp, 0.0);
    tiltController.Initialize(ut, yt, 0.0);
	printf("Time pan: %f\n", panController.GetTime() );
	printf("Time tilt: %f\n", tiltController.GetTime() );

	/* simple loop, the time is incremented by the integration method */
	while (panController.state != PositionControllerPan::finished && tiltController.state != PositionControllerTilt::finished)
	{
		/* call the submodel to calculate the output */
		panController.Calculate (up, yp);
        ut[0] = yp[0];
        tiltController.Calculate (ut, yt);
		printf("Time pan: %f\n", panController.GetTime() );
        printf("Time tilt: %f\n", tiltController.GetTime() );

	}

	/* perform the final calculations */
	panController.Terminate (up, yp);
    tiltController.Terminate (ut, yt);

	/* and we are done */
	return 0;
}

