/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  common\MotionProfiles.cpp
 *  subm:  FullController
 *  model: Jiwy-1
 *  expmt: Jiwy-1
 *  date:  June 15, 2026
 *  time:  11:04:42 AM
 *  user:  20-sim 5.1 Professional
 *  from:  Demo/Viewer License
 *  build: 5.1.6.14106
 **********************************************************/

/* This file implements the functions necessary for motion profiles
   functions
*/


