/**********************************************************
 * This file is generated by the 20-sim C++ Code Generator
 *
 *  file:  FullController.cpp
 *  subm:  FullController
 *  model: Jiwy-1
 *  expmt: Jiwy-1
 *  date:  June 15, 2026
 *  time:  11:04:42 AM
 *  user:  20-sim 5.1 Professional
 *  from:  Demo/Viewer License
 *  build: 5.1.6.14106
 **********************************************************/

/* Standard include files */
#include <stdio.h>
#include <math.h>
/* Include the header for memcpy and memset
 * You may need to change this into <memory.h> for older compilers
 */
#include <string.h>

/* 20-sim include files */
#include "FullController.h"

/* Delta margin used for end time checking */
const XXDouble c_delta = 1.0e-7;

/* this PRIVATE function sets the input variables from the input vector */
void FullController::CopyInputsToVariables (XXDouble *u)
{
	/* copy the input vector to the input variables */
	m_V[15] = u[0];		/* PosPan */
	m_V[16] = u[1];		/* PosTilt */
	m_V[17] = u[2];		/* RefPan */
	m_V[18] = u[3];		/* RefTilt */

}

/* this PRIVATE function uses the output variables to fill the output vector */
void FullController::CopyVariablesToOutputs (XXDouble *y)
{
	/* copy the output variables to the output vector */
	y[0] = 	m_V[13];		/* OutPan */
	y[1] = 	m_V[14];		/* OutTilt */

}

FullController::FullController(void)
{
	m_number_constants = 0;
	m_number_parameters = 14;
	m_number_initialvalues = 6;
	m_number_variables = 19;
	m_number_states = 6;
	m_number_rates = 6;
	m_number_matrices = 0;
	m_number_unnamed = 0;

	/* the variable arrays */
	m_C = new XXDouble[0 + 1];		/* constants */
	m_P = new XXDouble[14 + 1];		/* parameters */
	m_I = new XXDouble[6 + 1];		/* initial values */
	m_V = new XXDouble[19 + 1];		/* variables */
	m_s = new XXDouble[6 + 1];		/* states */
	m_R = new XXDouble[6 + 1];		/* rates (or new states) */
	m_M = new XXMatrix[0 + 1];		/* matrices */
	m_U = new XXDouble[0 + 1];		/* unnamed */
	m_workarray = new XXDouble[0 + 1];

	Reset(0.0);
	m_finish_time = 20.0;
}

void FullController::Reset(XXDouble starttime)
{
	m_start_time = starttime;
	m_step_size = 0.01;
	m_time = starttime;
	m_major = true;
	m_stop_run = false;

	/* Clear the allocated variable memory */
	memset(m_C, 0, (0 + 1) * sizeof(XXDouble));
	memset(m_P, 0, (14 + 1) * sizeof(XXDouble));
	memset(m_I, 0, (6 + 1) * sizeof(XXDouble));
	memset(m_V, 0, (19 + 1) * sizeof(XXDouble));
	memset(m_s, 0, (6 + 1) * sizeof(XXDouble));
	memset(m_R, 0, (6 + 1) * sizeof(XXDouble));
	memset(m_M, 0, (0 + 1) * sizeof(XXDouble));
	memset(m_U, 0, (0 + 1) * sizeof(XXDouble));
	memset(m_workarray, 0, (0 + 1) * sizeof(XXDouble));


	state = initialrun;
}

bool FullController::IsFinished(void)
{
	return (state == finished);
}

FullController::~FullController(void)
{
	/* free memory */
	delete[] m_C;
	delete[] m_P;
	delete[] m_I;
	delete[] m_V;
	delete[] m_s;
	delete[] m_R;
	delete[] m_M;
	delete[] m_U;
	delete[] m_workarray;
}

/* the initialization function for submodel */
void FullController::Initialize (XXDouble *u, XXDouble *y, XXDouble t)
{
	/* initialization phase (allocating memory) */
	m_initialize = true;
	m_stop_run = false;

	/* set the constants */


	/* set the parameters */
	m_P[0] = 0.0;		/* PositionControllerPan\corrGain\K */
	m_P[1] = 2.6;		/* PositionControllerPan\PID1\kp */
	m_P[2] = 0.05;		/* PositionControllerPan\PID1\tauD */
	m_P[3] = 0.17;		/* PositionControllerPan\PID1\beta */
	m_P[4] = 9.0;		/* PositionControllerPan\PID1\tauI */
	m_P[5] = -0.99;		/* PositionControllerPan\SignalLimiter2\minimum */
	m_P[6] = 0.99;		/* PositionControllerPan\SignalLimiter2\maximum */
	m_P[7] = 0.0;		/* PositionControllerTilt\corrGain\K */
	m_P[8] = 1.6;		/* PositionControllerTilt\PID1\kp */
	m_P[9] = 0.05;		/* PositionControllerTilt\PID1\tauD */
	m_P[10] = 0.001;		/* PositionControllerTilt\PID1\beta */
	m_P[11] = 10.5;		/* PositionControllerTilt\PID1\tauI */
	m_P[12] = -0.99;		/* PositionControllerTilt\SignalLimiter2\minimum */
	m_P[13] = 0.99;		/* PositionControllerTilt\SignalLimiter2\maximum */


	/* set the initial values */
	m_I[0] = 0.0;		/* PositionControllerPan\PID1\uD_previous_initial */
	m_I[1] = 0.0;		/* PositionControllerPan\PID1\error_previous_initial */
	m_I[2] = 0.0;		/* PositionControllerPan\PID1\uI_previous_initial */
	m_I[3] = 0.0;		/* PositionControllerTilt\PID1\uD_previous_initial */
	m_I[4] = 0.0;		/* PositionControllerTilt\PID1\error_previous_initial */
	m_I[5] = 0.0;		/* PositionControllerTilt\PID1\uI_previous_initial */


	/* set the states */
	m_s[0] = m_I[0];		/* PositionControllerPan\PID1\uD_previous */
	m_s[1] = m_I[1];		/* PositionControllerPan\PID1\error_previous */
	m_s[2] = m_I[2];		/* PositionControllerPan\PID1\uI_previous */
	m_s[3] = m_I[3];		/* PositionControllerTilt\PID1\uD_previous */
	m_s[4] = m_I[4];		/* PositionControllerTilt\PID1\error_previous */
	m_s[5] = m_I[5];		/* PositionControllerTilt\PID1\uI_previous */


	/* set the matrices */


	/* (re-)initialize the integration method */
	myintegmethod.Initialize(this);
	
	/* copy the inputs */
	m_time = t;
	CopyInputsToVariables (u);

	/* calculate initial equations */
	CalculateInitial ();

	/* set the states again, they might have changed in the initial calculation */
	m_s[0] = m_I[0];		/* PositionControllerPan\PID1\uD_previous */
	m_s[1] = m_I[1];		/* PositionControllerPan\PID1\error_previous */
	m_s[2] = m_I[2];		/* PositionControllerPan\PID1\uI_previous */
	m_s[3] = m_I[3];		/* PositionControllerTilt\PID1\uD_previous */
	m_s[4] = m_I[4];		/* PositionControllerTilt\PID1\error_previous */
	m_s[5] = m_I[5];		/* PositionControllerTilt\PID1\uI_previous */


	/* calculate static equations */
	CalculateStatic ();
	/* calculate input equations */
	CalculateInput ();
	/* calculate dynamic equations */
	CalculateDynamic ();
	/* calculate output equations */
	CalculateOutput ();

	/* Set the outputs */
	CopyVariablesToOutputs (y);

	/* end of initialization phase */
	m_initialize = false;

	state = mainrun;
}

/* the function that calculates the submodel */
void FullController::Calculate (XXDouble *u, XXDouble *y /*, XXDouble t*/)
{
	switch (state)
	{
		case initialrun:	/* calculate the model for the first time */
			Initialize(u, y, 0.0);
			break;
		case mainrun:	/* calculate the model */
			if ( ( m_time <= (m_finish_time - m_step_size  + c_delta )) || ( m_finish_time == 0.0 ) )
			{
				/* another precessor submodel could determine the parameters of this submodel
				   and therefore the static parameter calculations need to be performed. */
				CalculateStatic ();
				CopyInputsToVariables (u);
				CalculateInput ();
				myintegmethod.Step();
				CalculateOutput ();
				CopyVariablesToOutputs (y);
			}
			else
			{
				state = finished;
			}

			if ( ( m_stop_run == true ) || (( m_finish_time != 0.0 ) && ( m_time + c_delta >= m_finish_time)) )
			{
				state = finished;
			}
			break;
		case finished:
			break;
		default:
			break;
	}
}

/* the termination function for submodel */
void FullController::Terminate (XXDouble *u, XXDouble *y /*, XXDouble t */)
{
	/* copy the inputs */
	CopyInputsToVariables (u);

	/* calculate the final model equations */
	CalculateFinal ();

	/* set the outputs */
	CopyVariablesToOutputs (y);
}


/* This function calculates the initial equations of the model.
 * These equations are calculated before anything else
 */
void FullController::CalculateInitial (void)
{

}

/* This function calculates the static equations of the model.
 * These equations are only dependent from parameters and constants
 */
void FullController::CalculateStatic (void)
{

}

/* This function calculates the input equations of the model.
 * These equations are dynamic equations that must not change
 * in calls from the integration method (like random and delay).
 */
void FullController::CalculateInput (void)
{

}

/* This function calculates the dynamic equations of the model.
 * These equations are called from the integration method
 * to calculate the new model rates (that are then integrated).
 */
void FullController::CalculateDynamic (void)
{
	/* PositionControllerPan\PID1\factor = 1 / (sampletime + PositionControllerPan\PID1\tauD * PositionControllerPan\PID1\beta); */
	m_V[2] = 1.0 / (m_step_size + m_P[2] * m_P[3]);

	/* PositionControllerTilt\PID1\factor = 1 / (sampletime + PositionControllerTilt\PID1\tauD * PositionControllerTilt\PID1\beta); */
	m_V[8] = 1.0 / (m_step_size + m_P[9] * m_P[10]);

	/* PositionControllerPan\position = PosPan; */
	m_V[5] = m_V[15];

	/* PositionControllerTilt\position = PosTilt; */
	m_V[12] = m_V[16];

	/* PositionControllerPan\in = RefPan; */
	m_V[4] = m_V[17];

	/* PositionControllerTilt\in = RefTilt; */
	m_V[11] = m_V[18];

	/* PositionControllerTilt\PID1\error = PositionControllerTilt\in - PositionControllerTilt\position; */
	m_R[4] = m_V[11] - m_V[12];

	/* PositionControllerPan\corrGain\corr = PositionControllerPan\corrGain\K * PositionControllerPan\position; */
	m_V[0] = m_P[0] * m_V[5];

	/* PositionControllerPan\PID1\error = PositionControllerPan\in - PositionControllerPan\position; */
	m_R[1] = m_V[4] - m_V[5];

	/* PositionControllerTilt\PID1\uD = PositionControllerTilt\PID1\factor * (((PositionControllerTilt\PID1\tauD * PositionControllerTilt\PID1\uD_previous) * PositionControllerTilt\PID1\beta + (PositionControllerTilt\PID1\tauD * PositionControllerTilt\PID1\kp) * (PositionControllerTilt\PID1\error - PositionControllerTilt\PID1\error_previous)) + (sampletime * PositionControllerTilt\PID1\kp) * PositionControllerTilt\PID1\error); */
	m_R[3] = m_V[8] * (((m_P[9] * m_s[3]) * m_P[10] + (m_P[9] * m_P[8]) * (m_R[4] - m_s[4])) + (m_step_size * m_P[8]) * m_R[4]);

	/* PositionControllerTilt\PID1\uI = PositionControllerTilt\PID1\uI_previous + (sampletime * PositionControllerTilt\PID1\uD) / PositionControllerTilt\PID1\tauI; */
	m_R[5] = m_s[5] + (m_step_size * m_R[3]) / m_P[11];

	/* PositionControllerTilt\PID1\output = PositionControllerTilt\PID1\uI + PositionControllerTilt\PID1\uD; */
	m_V[7] = m_R[5] + m_R[3];

	/* PositionControllerPan\PID1\uD = PositionControllerPan\PID1\factor * (((PositionControllerPan\PID1\tauD * PositionControllerPan\PID1\uD_previous) * PositionControllerPan\PID1\beta + (PositionControllerPan\PID1\tauD * PositionControllerPan\PID1\kp) * (PositionControllerPan\PID1\error - PositionControllerPan\PID1\error_previous)) + (sampletime * PositionControllerPan\PID1\kp) * PositionControllerPan\PID1\error); */
	m_R[0] = m_V[2] * (((m_P[2] * m_s[0]) * m_P[3] + (m_P[2] * m_P[1]) * (m_R[1] - m_s[1])) + (m_step_size * m_P[1]) * m_R[1]);

	/* PositionControllerPan\PID1\uI = PositionControllerPan\PID1\uI_previous + (sampletime * PositionControllerPan\PID1\uD) / PositionControllerPan\PID1\tauI; */
	m_R[2] = m_s[2] + (m_step_size * m_R[0]) / m_P[4];

	/* PositionControllerPan\PID1\output = PositionControllerPan\PID1\uI + PositionControllerPan\PID1\uD; */
	m_V[1] = m_R[2] + m_R[0];

	/* PositionControllerPan\SignalLimiter2\output = if PositionControllerPan\PID1\output < PositionControllerPan\SignalLimiter2\minimum... ; */
	m_V[3] = ((m_V[1] < m_P[5]) ? 
		/* PositionControllerPan\SignalLimiter2\minimum */
		m_P[5]
	:
		/* if PositionControllerPan\PID1\output > PositionControllerPan\SignalLimiter2\maximum...  */
		((m_V[1] > m_P[6]) ? 
			/* PositionControllerPan\SignalLimiter2\maximum */
			m_P[6]
		:
			/* PositionControllerPan\PID1\output */
			m_V[1]
		)
	);

	/* PositionControllerTilt\corrGain\output = PositionControllerTilt\corrGain\K * PositionControllerPan\corrGain\corr; */
	m_V[6] = m_P[7] * m_V[0];

	/* PositionControllerTilt\PlusMinus1\output = PositionControllerTilt\corrGain\output + PositionControllerTilt\PID1\output; */
	m_V[9] = m_V[6] + m_V[7];

	/* PositionControllerTilt\SignalLimiter2\output = if PositionControllerTilt\PlusMinus1\output < PositionControllerTilt\SignalLimiter2\minimum... ; */
	m_V[10] = ((m_V[9] < m_P[12]) ? 
		/* PositionControllerTilt\SignalLimiter2\minimum */
		m_P[12]
	:
		/* if PositionControllerTilt\PlusMinus1\output > PositionControllerTilt\SignalLimiter2\maximum...  */
		((m_V[9] > m_P[13]) ? 
			/* PositionControllerTilt\SignalLimiter2\maximum */
			m_P[13]
		:
			/* PositionControllerTilt\PlusMinus1\output */
			m_V[9]
		)
	);

}

/* This function calculates the output equations of the model.
 * These equations are not needed for calculation of the rates
 * and are kept separate to make the dynamic set of equations smaller.
 * These dynamic equations are called often more than one time for each
 * integration step that is taken. This makes model computation much faster.
 */
void FullController::CalculateOutput (void)
{
	/* OutPan = PositionControllerPan\SignalLimiter2\output; */
	m_V[13] = m_V[3];

	/* OutTilt = PositionControllerTilt\SignalLimiter2\output; */
	m_V[14] = m_V[10];

}

/* This function calculates the final equations of the model.
 * These equations are calculated after all the calculations
 * are performed
 */
void FullController::CalculateFinal (void)
{

}



bool FullController::SetFinishTime(XXDouble newtime)
{
	if ((newtime <= 0.0) || ( newtime > m_time))
	{
		m_finish_time = newtime;
		return true;
	}

	return false;
}

